# Generated by Django 6.1 on 2026-08-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('retail', 'Retail & Online Seller'), ('fashion', 'Fashion'), ('beauty', 'Beauty / Cosmetics'), ('food', 'Food & Restaurants'), ('electronics', 'Electronics'), ('services', 'Services'), ('salon', 'Barber / Salon'), ('events', 'Event Planning'), ('photography', 'Photography'), ('cleaning', 'Cleaning Services'), ('repair', 'Repair Services'), ('wholesale', 'Wholesale'), ('pharmacy', 'Pharmacy'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)')], default='NGN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
    ]
