# Generated by Django 6.1 on 2026-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_phone_per_business',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('business', 'phone'), name='unique_customer_phone_per_business'),
        ),
    ]
