# Generated by Django 6.1 on 2026-08-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of the product cost at time of sale.', max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('pos', 'POS'), ('other', 'Other')], default='cash', max_length=20)),
                ('sale_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.product')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
