# Generated by Django 6.1 on 2026-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0002_remove_customer_unique_customer_phone_per_business_and_more'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'sale_date'], name='sales_sale_busines_3d57fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'customer'], name='sales_sale_busines_498a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'product'], name='sales_sale_busines_9b7513_idx'),
        ),
    ]
