# Generated by Django 6.1 on 2026-08-14 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inventory', 'Inventory'), ('transportation', 'Transportation'), ('marketing', 'Marketing'), ('rent', 'Rent'), ('salary', 'Salary'), ('utilities', 'Utilities'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('expense_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='businesses.business')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
