# Generated by Django 6.1 on 2026-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'expense_date'], name='expenses_ex_busines_42d27c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['business', 'category'], name='expenses_ex_busines_358a4b_idx'),
        ),
    ]
